### ISSUE TITLE
Add `rehype-slug` to post build

### ISSUE THREAD

**Issue by hgcl** [robinmetral/brut#24]
Would it be possible to add [rehype-slug](https://unifiedjs.com/explore/package/rehype-slug/) to the post build?

> This package is a [unified](https://unifiedjs.com/explore/package/unified/) ([rehype](https://unifiedjs.com/explore/project/rehypejs/rehype/)) plugin to add ids to headings. It looks for headings (so \<h1\> through \<h6\>) that do not yet have ids and adds id attributes to them based on the text they contain. The algorithm that does this is [github-slugger](https://github.com/Flet/github-slugger), which matches how GitHub works.

I feel like this is a common and useful pattern, wdyt? @robinmetral

**Comment by robinmetral** [comment]
I _think_ I added a mechanism to plug into the unified lifecycle, to support adding custom plugins. I kind of want to keep the number of plugins built into brut to a strict minimum. Will take a look next time I look at brut (might be a few months sorry)

**Comment by robinmetral** [comment]
> I _think_ I added a mechanism to plug into the unified lifecycle, to support adding custom plugins. I kind of want to keep the number of plugins built into brut to a strict minimum. Will take a look next time I look at brut (might be a few months sorry)

Wrong, I didn't. There is an issue for it: #12. Closing this since tackling #12 will solve this.

**Comment by robinmetral** [comment]
Actually I'm now thinking that rehype-slug should be part of the absolute minimum. Seems like a sensible default plugin to enable.
